spring.datasource.sqlScriptEncoding: UTF-8

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/testdb # file
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # In Memory(Default)
    username: sa
    password:
